// Define the type for the localConfig object
import { SiteConfig } from "./configTypes";

// Export the LocalConfig interface as an alias for backward compatibility
export type LocalConfig = SiteConfig;

const localConfig: LocalConfig = {
  showLogo: true,
  infoBar: {
    backgroundColor: "#e68bbe",
    phone: "(000) 000-0000",
    address: "Montgomery Crossroads Unit C, Savannah, GA 31406",
    hours: "Mon-Sat: 9:00 AM - 7:00 PM",
    textColor: "#ffffff",
    message: "Premium Nail Care Services Since 2018",
  },
  navBar: {
    backgroundColor: "#ffffff",
    textColor: "#e68bbe",
    logo: "TC-TITLE.png",
    showLogo: false,
    siteTitle: "Rose Petal Nails",
    siteTitleGradientFrom: "#eea1cd",
    siteTitleGradientTo: "#e68bbe",
    scheduleButtonText: "Book Appointment",
    scheduleButtonColor: "#e68bbe",
    activeTabColor: "#e68bbe",
    hamburgerIconColor: "#e68bbe",
    hamburgerIconHoverBgColor: "#eea1cd20",
    mobileMenuBgColor: "#ffffff",
    mobileNavTextColor: "#111827",
    mobileActiveTabBgColor: "#eea1cd20",
    mobileActiveTabTextColor: "#e68bbe",
    navLinks: [
      {
        path: "/",
        label: "Home",
      },
      {
        path: "/services",
        label: "Services",
      },
      {
        path: "/reviews",
        label: "Reviews",
      },
      {
        path: "/contact",
        label: "Contact",
      },
    ],
  },
  cursor: {
    enabled: true,
    mobileEnabled: false,
    cursorImage: "blkcursor.png",
    elementCursorImage: "blucursor.png",
  },
  loadingScreen: {
    enabled: false,
    backgroundColor: "#fde4f2",
    logoImage: "ed.png",
    logoWidth: 280,
    logoAlt: "Rose Petal Nails",
    spinner: {
      enabled: true,
      color: "#e68bbe",
      size: 60,
      thickness: 4,
    },
    timing: {
      minimumDisplayTime: 800,
      fadeOutDuration: 300,
    },
  },
  browser: {
    title: "Rose Petal Nails - Premium Nail Salon in Savannah, GA",
    shortTitle: "Rose Petal Nails",
    faviconFolder: "favicon",
    themeColor: "#e68bbe",
  },
  businessInfo: {
    name: "Rose Petal Nails",
    llcType: "",
    contactEmail: "info@rosepetalnails.com",
    contactPhone: "(912) 555-1234",
    legalPages: {
      privacyPolicy: {
        headerColor: "#e68bbe",
        linkColor: "#eea1cd",
        backgroundColor: "#ffffff",
        textColor: "#1f1f1f",
        borderColor: "#eea1cd",
        iconColor: "#e68bbe",
      },
      termsOfService: {
        headerColor: "#e68bbe",
        linkColor: "#eea1cd",
        backgroundColor: "#ffffff",
        textColor: "#1f1f1f",
        borderColor: "#eea1cd",
        disclaimerBgColor: "#fde4f2",
        disclaimerTextColor: "#e68bbe",
      },
    },
  },
  pages: {
    Home: {
      badge: "Premium Nail Care Since 2018",
      heroBadgeColor: "#eea1cd20",
      heroBadgeTitleColor: "#111827",
      title: "Rose Petal Nails in ",
      heroTitleColor: "#111827",
      location: "Savannah, GA",
      heroLocationColor: "#e68bbe",
      content: "",
      heroContentColor: "#111827",
      subtitle2:
        "Professional manicures, pedicures, nail art and luxury spa treatments by expert nail technicians in Savannah, GA.",
      heroSubtitleColor: "#6b7280",
      heroImage: "1.png",
      heroMobileImage: "mobile1.png",
      heroGradientTop: "#f4b8da",
      heroGradientBottom: "#ffffff",
      scheduleButtonText: "Book Appointment",
      heroScheduleButtonColor: "#e68bbe",
      heroScheduleButtonTextColor: "#ffffff",
      heroScheduleButtonHoverColor: "#f4b8da",
      contactButtonText: "Contact Us",
      heroContactButtonColor: "#00000000",
      heroContactButtonTextColor: "#ffffff",
      heroContactButtonBorderColor: "#ffffff",
      heroContactButtonHoverColor: "rgba(230, 139, 190, 0.41)",
      heroContactButtonHoverTextColor: "#e68bbe",
      heroContactButtonHoverBorderColor: "#e68bbe",
      heroCard1Text: "Affordable Pricing",
      heroBox1BgColor: "#e68bbe",
      heroBox1TextColor: "#ffffff",
      heroBox1BorderColor: "#f4b8da",
      heroBox1IconBgColor: "#f4b8da",
      heroBox1IconColor: "#e68bbe",
      heroCard2Text: "10+ Years Of Experience",
      heroBox2BgColor: "#e68bbe",
      heroBox2TextColor: "#ffffff",
      heroBox2BorderColor: "#f4b8da",
      heroBox2IconBgColor: "#f4b8da",
      heroBox2IconColor: "#e68bbe",
      heroCard3Text: "Quick & Detailed Work",
      heroBox3BgColor: "#e68bbe",
      heroBox3TextColor: "#ffffff",
      heroBox3BorderColor: "#f4b8da",
      heroBox3IconBgColor: "#f4b8da",
      heroBox3IconColor: "#e68bbe",
      scheduleSection: {
        scheduleSectionTitle: "BOOK YOUR APPOINTMENT",
        scheduleSectionTitleColor: "#e68bbe",
        scheduleSectionBadgeColor: "#eea1cd36",
        scheduleSectionBadgeTextColor: "#e68bbe",
        bookingTitle: "Schedule Your Nail Service",
        bookingTitleColor: "#e68bbe",
        scheduleTitlePart1: "Visit our luxury ",
        scheduleTitlePart1Color: "#111827",
        scheduleTitlePart2: "nail salon",
        scheduleTitlePart2Color: "#e68bbe",
        scheduleIconBgColor: "#eea1cd",
        scheduleIconColor: "#e68bbe",
        scheduleIconImage: "clock.png",
        scheduleAddress: "30 Montgomery Crossroads Unit C, Savannah, GA 31406",
        scheduleAddressColor: "#e68bbe",
        scheduleContent:
          "Professional nail salon specializing in luxury manicures, pedicures, gel services, and custom nail art with expert technicians and premium products.",
        scheduleContentColor: "#6b7280",
        calendarRippleStartColor: "#f4b8da",
        calendarRippleEndColor: "#e68bbe",
        calendarRippleOpacity: 0.15,
        calendarBgColor: "#ffffff",
        calendarBorderColor: "#f4b8da",
        calendarAccentColor: "#e68bbe",
        calendarMonth: "AUGUST",
        calendarYear: "2024",
        calendarEmptyDays: "3",
        calendarDaysInMonth: "31",
        calendarSelectedDay: "15",
        calendarAvailableDays: "5,8,12,15,19,22,26,29",
        calendarTimeSlotsText: "3 Time Slots Available",
        tapToBookText: "Tap to Book",
        tapToBookTextColor: "#000000",
        calendlyUrl: "https://calendly.com/*ENTER_NAIL_SALON_CALENDLY*",
        scheduleGradientTop: "#f4b8da",
        scheduleGradientBottom: "#ffffff",
      },
      guaranteeSection: {
        guaranteeTitle: "Why Choose Rose Petal Nails",
        guaranteeBadgeColor: "#eea1cdc0",
        guaranteeBadgeTextColor: "#e68bbe",
        guaranteeIcon1: "access.png",
        guaranteeTitle1: "Hygiene Excellence",
        guaranteeSubtitle1: "Hospital-Grade Sterilization",
        guaranteeIconBgColor1: "#ffffff",
        guaranteeIconBorderColor1: "#f4b8da",
        guaranteeTitleTextColor1: "#111827",
        guaranteeSubtitleTextColor1: "#6b7280",
        guaranteeIcon2: "free.png",
        guaranteeTitle2: "Licensed Professionals",
        guaranteeSubtitle2: "Expert Nail Technicians",
        guaranteeIconBgColor2: "#ffffff",
        guaranteeIconBorderColor2: "#f4b8da",
        guaranteeTitleTextColor2: "#111827",
        guaranteeSubtitleTextColor2: "#6b7280",
        guaranteeCenterLogo: "logo.png",
        guaranteeCenterBgColor: "#ffffff",
        guaranteeCenterBorderColor: "#f4b8da",
        guaranteeIcon4: "calculator.png",
        guaranteeTitle4: "Premium Products",
        guaranteeSubtitle4: "OPI, Essie & CND",
        guaranteeIconBgColor4: "#ffffff",
        guaranteeIconBorderColor4: "#eea1cd",
        guaranteeTitleTextColor4: "#111827",
        guaranteeSubtitleTextColor4: "#6b7280",
        guaranteeIcon5: "shipping.png",
        guaranteeTitle5: "Spa Atmosphere",
        guaranteeSubtitle5: "Relaxing & Luxurious",
        guaranteeIconBgColor5: "#ffffff",
        guaranteeIconBorderColor5: "#eea1cd",
        guaranteeTitleTextColor5: "#111827",
        guaranteeSubtitleTextColor5: "#6b7280",
        guaranteeIconBgColor: "#ffffff",
        guaranteeIconBorderColor: "#eea1cd",
        guaranteeTitleTextColor: "#111827",
        guaranteeSubtitleTextColor: "#6b7280",
        guaranteeBgGradientTop: "#fde4f2",
        guaranteeBgGradientBottom: "#fde4f2",
        guaranteeDecorativeElements: {
          topCircleFromColor: "#eea1cdec",
          topCircleToColor: "#e68bbe",
          topCircleOpacity: 0.3,
          bottomCircleFromColor: "#eea1cdec",
          bottomCircleToColor: "#e68bbe",
          bottomCircleOpacity: 0.3,
          centerRadialColor: "#ffffff",
          centerRadialOpacity: 0.8,
          item1BgFromColor: "#eea1cd",
          item1BgViaColor: "#e8a5b8",
          item1BgToColor: "#eea1cd",
          item2BgFromColor: "#eea1cd",
          item2BgViaColor: "#e8a5b8",
          item2BgToColor: "#eea1cd",
          centerBgFromColor: "#eea1cd",
          centerBgViaColor: "#e8a5b8",
          centerBgToColor: "#eea1cd",
          item4BgFromColor: "#eea1cd",
          item4BgViaColor: "#e8a5b8",
          item4BgToColor: "#eea1cd",
          item5BgFromColor: "#eea1cd",
          item5BgViaColor: "#e8a5b8",
          item5BgToColor: "#eea1cd",
          itemHoverFromColor: "#eea1cd",
          itemHoverToColor: "#e68bbe",
        },
      },
      servicesSection: {
        servicesBadgeText: "Our Specialties",
        servicesBadgeColor: "#eea1cdc0",
        servicesBadgeTextColor: "#e68bbe",
        servicesTitle: "Professional Nail Services",
        servicesHighlightText: "Nail Services",
        servicesTitleColor: "#111827",
        servicesHighlightColor: "#e68bbe",
        servicesHighlightUnderlineColor: "#eea1cd42",
        servicesDescription:
          "We specialize in luxury nail care and beauty treatments. Our expert technicians use premium products to deliver exceptional manicures, pedicures, and custom nail art in a relaxing spa atmosphere.",
        servicesDescriptionColor: "#6b7280",
        servicesButtonText: "View All Services",
        servicesButtonUrl: "/services",
        servicesButtonStartColor: "#e68bbe",
        servicesButtonEndColor: "#e68bbe",
        servicesButtonTextColor: "#ffffff",
        servicesButtonHoverStartColor: "#eea1cd",
        servicesButtonHoverEndColor: "#eea1cd",
        serviceReelCardBgColor: "#ffffff",
        serviceReelCardBorderColor: "#eea1cd80",
        serviceReelCardHoverShadowColor: "rgba(230, 139, 190, 0.15)",
        serviceReelIconColor: "#e68bbe",
        serviceReelTitleColor: "#111827",
        serviceReelTitleHoverColor: "#e68bbe",
        serviceReelDescriptionColor: "#6b7280",
        serviceReelDescriptionHoverColor: "#374151",
        serviceReelMobileIndicatorColor: "#e68bbe",
        serviceReelMobileInactiveColor: "#eea1cd",
        serviceReelGradientFromColor: "#ffffff",
        serviceReelGradientToColor: "#ffffff",
      },
      reviewsSection: {
        reviewsBadgeText: "Verified Google Reviews",
        reviewsBadgeColor: "rgba(255, 255, 255, 0.1)",
        reviewsBadgeTextColor: "#ffffff",
        reviewsTitle: "Reviews from our ",
        reviewsHighlight: "clients",
        reviewsTitleColor: "#000000",
        reviewsHighlightColor: "#000000",
        reviewsSubtitle: "Beautiful nails you can trust",
        reviewsSubtitleColor: "#000000",
        reviewCardBgColor: "rgba(255, 255, 255, 0.1)",
        reviewCardBorderColor: "rgba(255, 255, 255, 0.2)",
        reviewCardHoverBorderColor: "rgba(255, 255, 255, 0.3)",
        reviewTextColor: "#ffffff",
        reviewAuthorColor: "#ffffff",
        reviewVerifiedColor: "#ffffff",
        reviewStarColor: "#fbbf24",
        viewAllButtonText: "View All Reviews",
        viewAllButtonBgColor: "rgba(255, 255, 255, 0.1)",
        viewAllButtonHoverBgColor: "rgba(255, 255, 255, 0.2)",
        viewAllButtonTextColor: "#ffffff",
        viewAllButtonBorderColor: "rgba(255, 255, 255, 0.2)",
        reviewsBgStartColor: "#eea1cd",
        reviewsBgMiddleColor: "#e8a5b8",
        reviewsBgEndColor: "#e68bbe",
        defaultReviews: [
          {
            text: "Rose Petal Nails is absolutely amazing! I've been coming here for my gel manicures for months and the nail technicians are incredibly skilled. They always listen to what I want and create beautiful nail art. The salon is spotless and has such a relaxing spa atmosphere. The volcano pedicure is heavenly!",
            author: "Sarah M",
            rating: 5,
          },
          {
            text: "Best nail salon in Savannah! The staff is professional and so friendly. I got the most gorgeous SNS dipping powder manicure that lasted for weeks without any chipping. The attention to detail is incredible and they use high-quality OPI and Essie products. Worth every penny!",
            author: "Jessica R",
            rating: 5,
          },
          {
            text: "I can't recommend Rose Petal Nails enough! The milk & honey pedicure was so relaxing and my nails looked absolutely perfect. The technician was gentle and took her time to make sure everything was just right. The sterilization process is top-notch too. Will definitely be back!",
            author: "Amanda L",
            rating: 5,
          },
          {
            text: "Finally found my go-to nail salon! I got my nails done for my wedding here and they were absolutely stunning. The French manicure was flawless and lasted through my entire honeymoon. The staff made sure every detail was perfect and the rose gold accent nails were exactly what I envisioned. Thank you for making my special day even more beautiful!",
            author: "Maria S",
            rating: 5,
          },
          {
            text: "Love the custom nail art here!  I brought in a Pinterest photo and they recreated it perfectly with rhinestones and chrome accents. The quality is amazing - my nails still look salon-fresh after 2 weeks. The paraffin treatment made my hands so soft too. Definitely worth the drive from downtown Savannah!",
            author: "Brooklyn T",
            rating: 5,
          },
          {
            text: "Rose Petal Nails is my happy place! The spa pedicure is like a mini vacation - the massage chairs are so comfortable and the hot towel treatment is divine. I always leave feeling pampered and relaxed. My nail technician remembers exactly how I like my nails done every time. Exceptional service!",
            author: "Jennifer K",
            rating: 5,
          },
          {
            text: "I'm so impressed with the hygiene standards here. Every tool is sterilized and they use new files for each client. The gel manicure application is flawless - no bubbles, perfect coverage, and the color selection is incredible. I've tried several other salons but keep coming back to Rose Petal Nails for the quality and professionalism.",
            author: "Rachel D",
            rating: 5,
          },
          {
            text: "Brought my teenage daughter here for her first professional manicure and they were so patient and sweet with her. They explained every step and helped her choose the perfect ombre design. Now it's become our monthly mother-daughter tradition! The atmosphere is so welcoming and the nail art skills are incredible.",
            author: "Linda W",
            rating: 5,
          },
        ],
      },
      contactSection: {
        title: "Ready to Transform Your Nails?",
        titleColor: "#000000",
        subtitle:
          "Book your appointment today and experience the Rose Petal Nails difference with premium nail care and luxurious spa treatments.",
        subtitleColor: "#000000",
        buttonText: "Contact Us Now",
        buttonTextColor: "#e68bbe",
        buttonBgColor: "#ffffff",
        buttonHoverBgColor: "#eea1cd",
        buttonHoverTextColor: "#ffffff",
        sectionBgGradientFrom: "#f9cee7",
        sectionBgGradientVia: "#ffffff",
        sectionBgGradientTo: "#f9cee7",
        shimmerColor1: "#ffffff",
        shimmerColor2: "#eea1cd",
        shimmerColor3: "#ffffff",
        pulseIconColor: "#ffffff",
        decorativePattern: {
          patternColor: "#ffffff",
          patternOpacity: 0.1,
          patternSize: "24px",
        },
        clickIndicator: {
          enabled: true,
          text: "Click Here",
          textColor: "#ffffff",
          arrowColor: "#ffffff",
          pulseColor: "#ffffff",
        },
      },
    },
    Services: {
      title: "Premium Nail Services",
      heroTitleColor: "#ffffff",
      subtitle:
        "Professional nail salon providing luxury nail care and beauty services in Savannah, GA. Expert technicians using premium products since 2018.",
      heroSubtitleColor: "#ffffff",
      badge: "Premium Nail Care & Beauty Services Since 2018",
      heroBadgeBgColor: "#ffffff1a",
      heroBadgeTextColor: "#ffffff",
      heroBadgeIconColor: "#eea1cd",
      heroBadgeCheckmarkColor: "#eea1cd",
      heroBadgeMedalIconColor: "#eea1cd",
      card1Title: "Years Experience",
      card1Value: "7+",
      card2Title: "Clients Served",
      card2Value: "2000+",
      heroStatsCardBgColor: "#ffffff2f",
      heroStatsCardTextColor: "#ffffff",
      heroStatsCardValueColor: "#ffffff",
      heroStatsCardIconColor: "#eea1cd",
      heroImage: "/images/nail-services-hero.jpg",
      heroBgGradientFrom: "#e68bbe",
      heroBgGradientVia: "#e8a5b8",
      heroBgGradientTo: "#eea1cd",
      heroBlurredCircle1Color: "#e8a5b8",
      heroBlurredCircle2Color: "#eea1cd",
      heroPatternColor: "#ffffff",
      heroLightBeam1Color: "#e8a5b8",
      heroLightBeam2Color: "#eea1cd",
      serviceCategoriesBgColor: "#fde4f2",
      serviceCategoriesGradientOpacity: 0.7,
      serviceCategoriesBgColorFrom: "#fde4f2",
      serviceCategoriesBgColorTo: "#ffffff",
      serviceCategoryCardTitleColor: "#ffffff",
      serviceCategoryCardDescriptionColor: "#ffffff",
      serviceCategoryCardBorderColor: "#eea1cd",
      serviceCategoryCardButtonColor: "#ffffff",
      serviceCategoryCardButtonBgColor: "rgba(255, 255, 255, 0.1)",
      serviceCategoryCardButtonHoverBgColor: "#eea1cd",
      serviceCategoryCardButtonHoverColor: "#e68bbe",
      serviceCategories: [
        {
          id: "manicure",
          title: "Manicures",
          titleColor: "#ffffff",
          description:
            "Professional manicure services from classic to luxury gel options.",
          descriptionColor: "#ffffff",
          bgImage: "2.png",
          color: "#eea1cd-#ffffff",
          iconColor: "#ffffff",
          borderColor: "#eea1cd",
          icon: "SparklesIcon",
          services: [
            {
              title: "Classic Manicure",
              description:
                "Complete nail care with shaping, cuticle treatment, and polish application.",
              icon: "SparklesIcon",
              iconColor: "#e68bbe",
              titleColor: "#111827",
              descriptionColor: "#6b7280",
              bgColor: "#fde4f2",
              borderColor: "#eea1cd",
            },
            {
              title: "Gel Manicure",
              description:
                "Long-lasting gel polish that stays chip-free for up to 3 weeks.",
              icon: "SparklesIcon",
              iconColor: "#e68bbe",
              titleColor: "#111827",
              descriptionColor: "#6b7280",
              bgColor: "#fde4f2",
              borderColor: "#eea1cd",
            },
            {
              title: "French Manicure",
              description:
                "Timeless elegance with classic white tips and natural pink base.",
              icon: "SparklesIcon",
              iconColor: "#e68bbe",
              titleColor: "#111827",
              descriptionColor: "#6b7280",
              bgColor: "#fde4f2",
              borderColor: "#eea1cd",
            },
            {
              title: "SNS Dipping Powder",
              description:
                "Durable dip powder system fortified with vitamins for healthy, strong nails.",
              icon: "SparklesIcon",
              iconColor: "#e68bbe",
              titleColor: "#111827",
              descriptionColor: "#6b7280",
              bgColor: "#fde4f2",
              borderColor: "#eea1cd",
            },
            {
              title: "Paraffin Manicure",
              description:
                "Luxurious treatment with paraffin wax for ultimate hand moisturizing.",
              icon: "SparklesIcon",
              iconColor: "#e68bbe",
              titleColor: "#111827",
              descriptionColor: "#6b7280",
              bgColor: "#fde4f2",
              borderColor: "#eea1cd",
            },
          ],
        },
        {
          id: "pedicure",
          title: "Pedicures",
          titleColor: "#ffffff",
          description:
            "Relaxing foot care services from classic to luxury spa treatments.",
          descriptionColor: "#ffffff",
          bgImage: "3.png",
          color: "#eea1cd-#ffffff",
          iconColor: "#ffffff",
          borderColor: "#eea1cd",
          icon: "HeartIcon",
          services: [
            {
              title: "Classic Pedicure",
              description:
                "Complete foot care with soak, nail shaping, callus removal and polish.",
              icon: "HeartIcon",
              iconColor: "#e68bbe",
              titleColor: "#111827",
              descriptionColor: "#6b7280",
              bgColor: "#fde4f2",
              borderColor: "#eea1cd",
            },
            {
              title: "Spa Pedicure",
              description:
                "Luxury experience with exfoliation, mask, massage and hot towel treatment.",
              icon: "HeartIcon",
              iconColor: "#e68bbe",
              titleColor: "#111827",
              descriptionColor: "#6b7280",
              bgColor: "#fde4f2",
              borderColor: "#eea1cd",
            },
            {
              title: "Volcano Pedicure",
              description:
                "Detoxifying treatment with volcano crystals, sugar scrub and collagen mask.",
              icon: "HeartIcon",
              iconColor: "#e68bbe",
              titleColor: "#111827",
              descriptionColor: "#6b7280",
              bgColor: "#fde4f2",
              borderColor: "#eea1cd",
            },
            {
              title: "Milk & Honey Pedicure",
              description:
                "Nourishing treatment with goat milk soak, butter scrub and eucalyptus oil.",
              icon: "HeartIcon",
              iconColor: "#e68bbe",
              titleColor: "#111827",
              descriptionColor: "#6b7280",
              bgColor: "#fde4f2",
              borderColor: "#eea1cd",
            },
            {
              title: "Gel Pedicure",
              description:
                "Long-lasting gel polish application for beautiful, chip-resistant toes.",
              icon: "HeartIcon",
              iconColor: "#e68bbe",
              titleColor: "#111827",
              descriptionColor: "#6b7280",
              bgColor: "#fde4f2",
              borderColor: "#eea1cd",
            },
          ],
        },
        {
          id: "nail-art",
          title: "Nail Art & Design",
          titleColor: "#ffffff",
          description:
            "Creative nail art and custom designs to express your unique style.",
          descriptionColor: "#ffffff",
          bgImage: "4.png",
          color: "#eea1cd-#ffffff",
          iconColor: "#ffffff",
          borderColor: "#eea1cd",
          icon: "PaintBrushIcon",
          services: [
            {
              title: "Custom Nail Art",
              description:
                "Personalized designs created by our skilled artists using premium materials.",
              icon: "PaintBrushIcon",
              iconColor: "#e68bbe",
              titleColor: "#111827",
              descriptionColor: "#6b7280",
              bgColor: "#fde4f2",
              borderColor: "#eea1cd",
            },
            {
              title: "Rhinestone & Crystal",
              description:
                "Elegant embellishments with high-quality crystals and rhinestones.",
              icon: "PaintBrushIcon",
              iconColor: "#e68bbe",
              titleColor: "#111827",
              descriptionColor: "#6b7280",
              bgColor: "#fde4f2",
              borderColor: "#eea1cd",
            },
            {
              title: "Chrome & Holographic",
              description:
                "Modern mirror finish and holographic effects for stunning visual impact.",
              icon: "PaintBrushIcon",
              iconColor: "#e68bbe",
              titleColor: "#111827",
              descriptionColor: "#6b7280",
              bgColor: "#fde4f2",
              borderColor: "#eea1cd",
            },
            {
              title: "Ombre Design",
              description:
                "Beautiful gradient color blending from light to dark or color to color.",
              icon: "PaintBrushIcon",
              iconColor: "#e68bbe",
              titleColor: "#111827",
              descriptionColor: "#6b7280",
              bgColor: "#fde4f2",
              borderColor: "#eea1cd",
            },
            {
              title: "Seasonal Designs",
              description:
                "Trendy seasonal artwork perfect for holidays and special occasions.",
              icon: "PaintBrushIcon",
              iconColor: "#e68bbe",
              titleColor: "#111827",
              descriptionColor: "#6b7280",
              bgColor: "#fde4f2",
              borderColor: "#eea1cd",
            },
          ],
        },
      ],
      ctaBgGradientFrom: "#e68bbe",
      ctaBgGradientVia: "#e8a5b8",
      ctaBgGradientTo: "#eea1cd",
      ctaBgPatternColor: "#ffffff60",
      ctaCardBgColor: "#ffffff2f",
      ctaCardBorderColor: "#ffffff20",
      scheduleButtonText: "Book Appointment",
      scheduleButtonBgColor: "#ffffff",
      scheduleButtonTextColor: "#e68bbe",
      scheduleButtonHoverBgColor: "#f3f4f6",
      callButtonText: "Call Us Now",
      callButtonBgColor: "#e68bbe",
      callButtonTextColor: "#ffffff",
      callButtonHoverBgColor: "#e8a5b8",
      ctaTitle: "Ready for Beautiful Nails?",
      ctaTitleColor: "#ffffff",
      ctaDescription:
        "Contact us today for professional nail care, manicures, pedicures, and nail art services at competitive prices in Savannah, GA.",
      ctaDescriptionColor: "#ffffff",
    },
    Reviews: {
      title: "Customer Reviews",
      heroTitleColor: "#ffffff",
      subtitle:
        "We're proud of the beautiful nail work we do and the trust our clients place in us. Here's what they have to say about their experience at Rose Petal Nails.",
      heroSubtitleColor: "#ffffff",
      badge: "Verified Google Reviews",
      heroBadgeBgColor: "#ffffff10",
      heroBadgeTextColor: "#ffffff",
      heroBadgeIconColor: "#eea1cd",
      heroBadgeCheckmarkColor: "#eea1cd",
      heroBadgeBorderColor: "#eea1cd",
      statsCard1Title: "Verified Reviews",
      statsCard1IconColor: "#eea1cd",
      statsCard1BlurGradientFrom: "#e68bbe",
      statsCard1BlurGradientTo: "#e8a5b8",
      statsCard2Title: "Average Rating",
      statsCard2IconColor: "#facc15",
      statsCard2BlurGradientFrom: "#e8a5b8",
      statsCard2BlurGradientTo: "#e68bbe",
      statsCardBgColor: "#ffffff10",
      statsCardTextColor: "#f3f4f6",
      statsCardTitleColor: "#ffffff",
      statsCardBorderColor: "#ffffff20",
      statsCardHoverBorderColor: "#ffffff30",
      heroImage: "/images/nail-reviews-hero.jpg",
      heroBgGradientFrom: "#e68bbe",
      heroBgGradientVia: "#e8a5b8",
      heroBgGradientTo: "#eea1cd",
      heroBlurredCircle1Color: "#e8a5b8",
      heroBlurredCircle2Color: "#eea1cd",
      heroBlurredCircle3Color: "#f8d7da",
      heroLightBeam1Color: "#e8a5b8",
      heroLightBeam2Color: "#eea1cd",
      heroPatternColor: "#ffffff",
      heroPatternOpacity: 0.1,
      reviewsSectionBgColor: "#fde4f2",
      reviewCardBgColor: "#ffffff",
      reviewCardHoverShadow: "lg",
      reviewCardBorderColor: "#eea1cd",
      reviewCardTextColor: "#4b5563",
      reviewCardAuthorNameColor: "#111827",
      reviewCardSourceColor: "#6b7280",
      reviewCardStarColor: "#facc15",
      reviewCardStarEmptyColor: "#eea1cd",
      reviewCardShowMoreColor: "#e68bbe",
      reviewCardShowMoreHoverColor: "#e8a5b8",
      reviewCardGradientColor: "#e68bbe",
      reviewAvatarColors: [
        "#e68bbe",
        "#e8a5b8",
        "#eea1cd",
        "#f8d7da",
        "#fce4ec",
        "#e68bbe",
        "#e8a5b8",
        "#eea1cd",
      ],
      reviewAvatarTextColor: "#ffffff",
      paginationButtonBgColor: "#e68bbe",
      paginationButtonTextColor: "#ffffff",
      paginationButtonDisabledOpacity: 0.5,
      paginationTextColor: "#4b5563",
      shareExperienceBgColor: "#ffffff",
      shareExperienceBorderColor: "#eea1cd",
      shareExperienceShadow: "sm",
      shareExperienceHoverShadow: "md",
      shareExperienceTitleColor: "#111827",
      shareExperienceSubtitleColor: "#4b5563",
      shareExperienceGradientColor: "#e68bbe",
      shareExperienceGradientOpacity: 0.5,
      shareButtonBgColor: "#e68bbe",
      shareButtonTextColor: "#ffffff",
      shareButtonHoverBgColor: "#e8a5b8",
      shareButtonShadow: "sm",
      shareButtonHoverShadow: "md",
      shareButtonText: "Write a Review on Google",
      shareButtonLink: "https://g.co/kgs/Sh3fpBf",
      shareExperienceTitle: "Share Your Experience",
      shareExperienceSubtitle:
        "Help others by sharing your nail salon experience with us",
      ctaBgGradientFrom: "#e68bbe",
      ctaBgGradientVia: "#e8a5b8",
      ctaBgGradientTo: "#eea1cd",
      ctaPatternColor: "#ffffff",
      ctaPatternOpacity: 0.05,
      ctaCardBgColor: "#ffffff0d",
      ctaCardBlurAmount: "2px",
      ctaScheduleButtonText: "Book Appointment",
      ctaScheduleButtonBgColor: "#ffffff",
      ctaScheduleButtonTextColor: "#e68bbe",
      ctaScheduleButtonHoverBgColor: "#f3f4f6",
      ctaCallButtonText: "Call Us Now",
      ctaCallButtonBgColor: "#ffffff",
      ctaCallButtonTextColor: "#e68bbe",
      ctaCallButtonHoverBgColor: "#eea1cd",
      ctaTitle: "Ready for Beautiful Nails?",
      ctaTitleColor: "#ffffff",
      ctaDescription:
        "Schedule your appointment today and experience the Rose Petal Nails difference with premium nail care services.",
      ctaDescriptionColor: "#ffffff",
    },
    Careers: {
      heroPaddingTop: "150px",
      heroBgGradientFrom: "#e68bbe",
      heroBgGradientVia: "#e8a5b8",
      heroBgGradientTo: "#eea1cd",
      heroBlurredCircle1Color: "#e8a5b8",
      heroBlurredCircle1Opacity: 0.2,
      heroBlurredCircle2Color: "#eea1cd",
      heroBlurredCircle2Opacity: 0.2,
      heroPatternColor: "#ffffff",
      heroPatternOpacity: 0.3,
      waveSeparatorColor: "#e68bbe81",
      waveSeparatorHeight: "250px",
      applicationSectionBgColor: "#fde4f2",
      applicationFormShadow: "0 25px 50px -12px rgba(230, 139, 190, 0.25)",
      hireBadgeText: "We're hiring passionate nail technicians",
      hireBadgeBgColor: "#ffffff10",
      hireBadgeBorderColor: "#ffffff20",
      hireBadgeTextColor: "#ffffff",
      hireTitle: "Join Our Team",
      hireTitleColor: "#ffffff",
      hireTitleHighlightColor: "#ffffff",
      hireTitleGlowColor: "#ffffff",
      hireTitleGlowOpacity: 0.3,
      hireSubtitle:
        "Build your career with Rose Petal Nails. We're looking for talented individuals who are passionate about nail care, beauty services, and exceptional customer service.",
      hireSubtitleColor: "#ffffff",
      hireSubtitleOpacity: 0.9,
      formHeaderBgFrom: "#e68bbe",
      formHeaderBgTo: "#e8a5b8",
      formHeaderPatternColor: "#ffffff",
      formHeaderPatternOpacity: 0.15,
      formHeaderPatternSize: "16px",
      formHeaderTitleText: "Application Form",
      formHeaderTitleColor: "#ffffff",
      formHeaderSubtitleText:
        "Fill out the form below to apply for a position with our nail salon team",
      formHeaderSubtitleColor: "#ffffff",
      formHeaderSubtitleOpacity: 0.8,
      formSectionBgColor: "#ffffff",
      formSectionBorderColor: "#eea1cd",
      formSectionTitleColor: "#e68bbe",
      formSectionHoverShadow: "md",
      formInputBgColor: "#ffffff",
      formInputBorderColor: "#eea1cd",
      formInputTextColor: "#111827",
      formInputFocusRingColor: "#e68bbe",
      formInputFocusBorderColor: "#e68bbe",
      formInputBorderRadius: "xl",
      formInputPadding: "px-4 py-3",
      formLabelColor: "#374151",
      formErrorColor: "#ef4444",
      positionOptions: [
        "Nail Technician",
        "Manicurist",
        "Pedicurist",
        "Nail Artist",
        "Front Desk / Receptionist",
        "Salon Assistant",
        "Other",
      ],
      addReferenceBtnBgColor: "#e68bbe",
      addReferenceBtnHoverBgColor: "#e8a5b8",
      addReferenceBtnTextColor: "#ffffff",
      removeReferenceBtnColor: "#ef4444",
      removeReferenceBtnHoverColor: "#dc2626",
      submitButtonBgFrom: "#e68bbe",
      submitButtonBgTo: "#e8a5b8",
      submitButtonTextColor: "#ffffff",
      submitButtonHoverShadow: "xl",
      submitButtonBorderRadius: "xl",
      successMessageBgColor: "#fde4f2",
      successMessageBorderColor: "#eea1cd",
      successMessageTextColor: "#e68bbe",
      errorMessageBgColor: "#fef2f2",
      errorMessageBorderColor: "#fecaca",
      errorMessageTextColor: "#991b1b",
      mobileOverlay: {
        enabled: true,
        mobileBreakpoint: 663,
        title: "Desktop View Required",
        message:
          "Our job application form requires a larger screen. Please visit this page on a desktop or laptop computer for the best experience.",
        buttonText: "Back to Home Page",
        buttonLink: "/",
        footerText:
          "If you're already on a desktop device, please increase your browser window size.",
        backgroundOpacity: 0.9,
        overlayZIndex: 50,
        cardBackgroundColor: "#ffffff",
        cardBorderRadius: "2xl",
        cardBorderTopWidth: 4,
        cardBorderTopColor: "#e68bbe",
        cardBoxShadow: "2xl",
        iconBackgroundOpacity: 0.3,
        iconColor: "#e68bbe",
        iconBgColor: "#fde4f2",
        iconWidth: 20,
        iconHeight: 20,
        titleFontSize: "2xl",
        titleFontWeight: "bold",
        messageColor: "#4b5563",
        buttonWidth: "full",
        buttonPadding: "py-3 px-4",
        buttonBgColor: "#e68bbe",
        buttonTextColor: "#ffffff",
        buttonFontWeight: "medium",
        buttonBorderRadius: "lg",
        buttonShadow: "md",
        buttonHoverScale: 1.05,
        buttonTapScale: 0.95,
        footerMarginTop: 6,
        footerPaddingTop: 6,
        footerBorderColor: "#e5e7eb",
        footerTextColor: "#6b7280",
        footerTextSize: "sm",
      },
    },
    Contact: {
      title: "Get in Touch",
      heroTitleColor: "#ffffff",
      heroTitleGradientFrom: "#ffffff",
      heroTitleGradientVia: "#ffffff",
      heroTitleGradientTo: "#ffffff",
      heroTitleGlowColor: "#eea1cd",
      heroTitleGlowOpacity: 0.3,
      subtitle:
        "Need nail care services? Have questions about our treatments? We're here to help make your nails beautiful and provide exceptional service.",
      heroSubtitleColor: "#ffffff",
      heroSubtitleHighlightBgColor: "#e68bbe",
      badge: "Premium Nail Care Guaranteed",
      heroBadgeBgColor: "#ffffff1a",
      heroBadgeTextColor: "#ffffff",
      heroBadgeIconColor: "#eea1cd",
      heroBadgeBorderColor: "#ffffff33",
      featureBadge1Text: "Licensed Technicians",
      featureBadge1IconColor: "#eea1cd",
      featureBadge1BgColor: "#ffffff1a",
      featureBadge1BorderColor: "#ffffff33",
      featureBadge1TextColor: "#ffffff",
      featureBadge2Text: "Premium Products",
      featureBadge2IconColor: "#eea1cd",
      featureBadge2BgColor: "#ffffff1a",
      featureBadge2BorderColor: "#ffffff33",
      featureBadge2TextColor: "#ffffff",
      heroImage: "/images/nail-contact-hero.jpg",
      heroBgGradientFrom: "#e68bbe",
      heroBgGradientVia: "#e8a5b8",
      heroBgGradientTo: "#eea1cd",
      heroBlurredCircle1Color: "#e8a5b8",
      heroBlurredCircle1Opacity: 0.2,
      heroBlurredCircle2Color: "#eea1cd",
      heroBlurredCircle2Opacity: 0.2,
      heroPatternColor: "#ffffff",
      heroPatternOpacity: 0.3,
      heroLightBeam1Color: "#e8a5b8",
      heroLightBeam1Opacity: 0.2,
      heroLightBeam2Color: "#eea1cd",
      heroLightBeam2Opacity: 0.2,
      contactSectionBgColor: "#fde4f2",
      contactInfoTitleText: "Contact Information",
      contactInfoTitleColor: "#e68bbe",
      contactIconBgColor: "#eea1cd42",
      contactIconColor: "#e68bbe",
      contactLabelColor: "#111827",
      contactTextColor: "#4b5563",
      contactLinkHoverColor: "#e8a5b8",
      phoneIcon: "PhoneIcon",
      phoneLabel: "Phone",
      phoneNumber: "(912) 555-1234",
      phoneNumberLink: "tel:+19125551234",
      emailIcon: "EnvelopeIcon",
      emailLabel: "Email",
      emailAddress: "info@rosepetalnails.com",
      emailAddressLink: "mailto:info@rosepetalnails.com",
      locationIcon: "MapPinIcon",
      locationLabel: "Location",
      locationAddress: "30 Montgomery Crossroads Unit C,\nSavannah, GA 31406",
      hoursIcon: "ClockIcon",
      hoursLabel: "Business Hours",
      hoursText:
        "Monday - Friday: 9:00 AM - 7:00 PM\nSaturday: 9:00 AM - 5:00 PM\nSunday: Closed",
      googleMapEmbedUrl:
        "https://www.google.com/maps/embed?pb=*ENTER_GMAPS_URL*",
      googleMapHeight: "300px",
      googleMapBorderRadius: "lg",
      googleMapShadow: "lg",
      formTitleText: "Send Us a Message",
      formTitleColor: "#111827",
      formLabelColor: "#374151",
      formInputBgColor: "#ffffff",
      formInputBorderColor: "#eea1cd",
      formInputTextColor: "#111827",
      formInputFocusRingColor: "#e68bbe",
      formInputBorderRadius: "lg",
      formInputPadding: "px-4 py-3",
      formFieldFullName: "Full Name",
      formFieldEmail: "Email Address",
      formFieldPhone: "Phone Number",
      formFieldService: "Service Needed",
      formFieldMessage: "Message",
      serviceOptions: [
        "General Inquiry",
        "Manicures",
        "Pedicures",
        "Nail Art",
        "Special Events",
        "Gel Services",
        "Free Consultation",
      ],
      formSubmitBtnText: "Send Message",
      formSubmitBtnBgColor: "#e68bbe",
      formSubmitBtnTextColor: "#ffffff",
      formSubmitBtnHoverBgColor: "#e8a5b8",
      formSubmitBtnBorderRadius: "lg",
      ctaBgGradientFrom: "#e68bbe",
      ctaBgGradientVia: "#e8a5b8",
      ctaBgGradientTo: "#eea1cd",
      ctaPatternColor: "#ffffff",
      ctaPatternOpacity: 0.05,
      ctaCardBgColor: "#ffffff0d",
      ctaCardBlurAmount: "2px",
      ctaScheduleButtonText: "Book Appointment",
      ctaScheduleButtonBgColor: "#ffffff",
      ctaScheduleButtonTextColor: "#e68bbe",
      ctaScheduleButtonHoverBgColor: "#f3f4f6",
      ctaCallButtonText: "Call Us Now",
      ctaCallButtonBgColor: "#ffffff",
      ctaCallButtonTextColor: "#e68bbe",
      ctaCallButtonHoverBgColor: "#eea1cd",
      ctaTitle: "Ready for Beautiful Nails?",
      ctaTitleColor: "#ffffff",
      ctaDescription:
        "Schedule your appointment today and experience the Rose Petal Nails difference with premium nail care and beauty services.",
      ctaDescriptionColor: "#ffffff",
    },
  },
  theme: {
    primary600: "#f4b8da",
    primary700: "#e68bbe",
  },
  navLinks: [
    {
      path: "/",
      label: "Home",
    },
    {
      path: "/services",
      label: "Services",
    },
    {
      path: "/reviews",
      label: "Reviews",
    },
    {
      path: "/contact",
      label: "Contact",
    },
  ],
  policies: {
    terms: "Our terms of service text here.",
    privacy: "Our privacy policy text here.",
  },
  description:
    "Professional nail salon in Savannah, GA - Premium nail care & beauty services",
  contactInfo: {
    address: "30 Montgomery Crossroads Unit C, Savannah, GA 31406",
    phone: "(912) 555-1234",
    email: "info@rosepetalnails.com",
  },
  hours: {
    weekday: "Monday - Friday: 9:00 AM - 7:00 PM",
    weekend: "Saturday: 9:00 AM - 5:00 PM, Sunday: Closed",
  },
  footerLinks: [
    {
      path: "/",
      label: "Home",
    },
    {
      path: "/services",
      label: "Services",
    },
    {
      path: "/reviews",
      label: "Reviews",
    },
    {
      path: "/contact",
      label: "Contact",
    },
  ],
  socialLinks: {
    twitter: "https://twitter.com/rosepetalnails",
    facebook: "https://facebook.com/rosepetalnails",
    linkedin: "https://linkedin.com/company/rosepetalnails",
    instagram: "https://instagram.com/rosepetalnails",
  },
  showJoinTeamButton: true,
  joinTeamText: "Join the Team",
  joinTeamLink: "/careers",
  copyright: "© 2025 Rose Petal Nails. All rights reserved.",
  footerStyle: {
    backgroundColor: "#ffffff",
    gradientFromColor: "#f9cee7",
    gradientToColor: "#ffffff",
    titleColor: "#e68bbe",
    textColor: "#111827",
    linkColor: "#e68bbe",
    linkHoverColor: "#f4b8da",
    socialIconColor: "#e68bbe",
    dividerColor: "rgba(230, 139, 190, 0.2)",
    quickLinksTitleColor: "#e68bbe",
    contactInfoTitleColor: "#e68bbe",
    infoTitleColor: "#e68bbe",
    joinButtonBgColor: "#e68bbe",
    joinButtonTextColor: "#ffffff",
    joinButtonHoverBgColor: "#f4b8da",
    hoursCardBgColor: "rgba(230, 139, 190, 0.04)",
    hoursCardTextColor: "#111827",
    hoursCardValueColor: "#e68bbe",
    copyrightTextColor: "#6b7280",
    policyLinkColor: "#e68bbe",
    policyLinkHoverColor: "#f4b8da",
  },
  schedulingButtonText: "Book Appointment",
  themeColor: "#e68bbe",
  themeLink: "",
  companyName: "Rose Petal Nails",
};

export default localConfig;
